# This is a basic workflow to help you get started with Actions

name: CI

env:
  BRANCH_NAME: "${{github.ref_name}}"
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "task1" branch
  push:
    branches: [ $BRANCH_NAME ]
  pull_request:
    branches: [ $BRANCH_NAME ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x']
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
        working-directory: SpaceBattle
      - name: Build
        run: dotnet build
        working-directory: SpaceBattle
      - name: Test
        run: dotnet test
        working-directory: SpaceBattle.Tests
